apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ego.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ego.name" . }}
    helm.sh/chart: {{ include "ego.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ego.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ego.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "ego.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.appConfig.activeProfiles }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTID
              value: {{ .Values.appConfig.googleClientID }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: google-client-secret
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_AUTHORIZATIONURI
              value: {{ .Values.appConfig.googleAuthorizationUri }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECTURI
              value: "https://{{ .Values.appConfig.host }}{{ .Values.appConfig.apiPath }}/oauth/code/google"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ORCID_CLIENTID
              value: {{ .Values.appConfig.orcidClientID }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ORCID_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: orcid-client-secret
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ORCID_REDIRECTURI
              value: "https://{{ .Values.appConfig.host }}{{ .Values.appConfig.apiPath }}/oauth/code/orcid"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_LINKEDIN_CLIENTID
              value: {{ .Values.appConfig.linkedInClientID }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_LINKEDIN_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: linkedin-client-secret
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_LINKEDIN_REDIRECTURI
              value: "https://{{ .Values.appConfig.host }}{{ .Values.appConfig.apiPath }}/oauth/code/linkedin"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENTID
              value: {{ .Values.appConfig.githubClientID }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: github-client-secret
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_REDIRECTURI
              value: "https://{{ .Values.appConfig.host }}{{ .Values.appConfig.apiPath }}/oauth/code/github"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENTID
              value: {{ .Values.appConfig.facebookClientID | quote }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: facebook-client-secret
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_REDIRECTURI
              value: "https://{{ .Values.appConfig.host }}{{ .Values.appConfig.apiPath }}/oauth/code/facebook"
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.appConfig.databaseUrl }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.appConfig.psqlUsername }}
            {{- if .Values.appConfig.psqlSecretName }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appConfig.psqlSecretName }}
                  key: {{ .Values.appConfig.psqlSecretKey }}
            {{- end  }}
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: SPRING_FLYWAY_LOCATIONS
              value: "classpath:flyway/sql,classpath:db/migration"
            - name: SPRING_FLYWAY_PLACEHOLDERS_DEFAULT-PROVIDER
              value: {{ .Values.appConfig.defaultProvider }}
            - name: SWAGGER_HOST
              value: {{ .Values.appConfig.swaggerHost }}
            - name: SWAGGER_BASEURL
              value: {{ .Values.appConfig.swaggerBaseUrl }}
            - name: APITOKEN_DURATIONDAYS
              value: {{ .Values.appConfig.apiTokenDurationDays | quote }}
            - name: JWT_USER_DURATIONMS
              value: {{ .Values.appConfig.jwt.userDurationMs | quote }}
            - name: JWT_APP_DURATIONMS
              value: {{ .Values.appConfig.jwt.appDurationMs | quote }}
            - name: REFRESHTOKEN_DURATIONMS
              value: {{ .Values.appConfig.refreshToken.durationMs | quote }}
            - name: REFRESHTOKEN_COOKIEISSECURE
              value: {{ .Values.appConfig.refreshToken.cookieIsSecure | quote }}
            - name: REFRESHTOKEN_DOMAIN
              value: {{ .Values.appConfig.host }}
            - name: KEYCLOAK_CLIENT_CLIENTID
              value: {{ .Values.appConfig.keycloakClientID }}
            - name: KEYCLOAK_CLIENT_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: keycloak-client-secret
            - name: KEYCLOAK_CLIENT_PREESTABLISHEDREDIRECTURI
              value: "https://{{ .Values.appConfig.host }}{{ .Values.appConfig.apiPath }}/oauth/login/keycloak"
          {{- if .Values.extraEnv }}
            {{ range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.uiImage.repository }}:{{ .Values.uiImage.tag }}"
          imagePullPolicy: {{ .Values.uiImage.pullPolicy }}
          env:
            - name: REACT_APP_API
              value: "https://{{ .Values.appConfig.host }}{{ .Values.appConfig.apiPath }}"
            - name: REACT_APP_EGO_CLIENT_ID
              value: {{ .Values.appConfig.egoClientId }}
            - name: REACT_APP_KEYCLOAK_ENABLED
              value: {{ .Values.appConfig.uiKeycloakEnabled | quote }}
            - name: REACT_APP_PASSPORT_ENABLED
              value: {{ .Values.appConfig.uiPassportEnabled | quote }}
          ports:
            - name: http-ui
              containerPort: 8080
              protocol: TCP
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
