# Default values for score.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: overture/score-server
  tag: 3.0.1
  ImagePullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - score.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv: {}

appConfig:
  springProfiles: amazon,collaboratory,prod,secure
  authServer:
    clientId: 
    clientSecret: 
    url: https://ego.local/api/o/check_token
    tokenName: token
    scope:
      download:
        system: aws.download
        study:
          prefix: aws.
          suffix: .download
      upload:
        system: aws.upload
        study:
          prefix: aws.
          suffix: .upload
  objectStorage:
    accessKey: 
    secretKey: 
    url: https://object.local
    sigV4Enabled: true
  song:  
    serverUrl: https://song.local
  storageServer:
    dataBucket: qa.icgc
    dataDir: data
    sentinel: heliograph
    port: "8080"
    stateBucket: qa.icgc
    partSize: "1073741824"
    connectionTimeout: "1200000"

podSecurityContext:
  runAsGroup: 9999
  runAsNonRoot: true
  runAsUser: 9999
